services:
  - type: web
    name: TaskTrackerApp
    runtime: dotnet
    runtimeVersion: 10.0
    buildCommand: dotnet publish TaskTrackerApp -c Release -o out
    startCommand: dotnet out/TaskTrackerApp.dll
    envVars:
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:10000
      - key: ASPNETCORE_ENVIRONMENT
        value: production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:10000
